import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';

// This file will be generated by build_runner.
// Run: flutter pub run build_runner build
// Generated file: vault_database.g.dart

part 'vault_database.g.dart';

// ============================================================================
// TABLE DEFINITIONS
// ============================================================================

/// Photos table: encrypted photo metadata including file paths, keys, and checksums.
@DataClassName('VaultPhoto')
class Photos extends Table {
  TextColumn get id => text()();
  TextColumn get originalFilename => text()();
  IntColumn get createdTimeMs => integer()();
  IntColumn get importedTimeMs => integer()();
  IntColumn get modifiedTimeMs => integer()();
  TextColumn get source =>
      text()(); // 'camera', 'gallery', 'file_picker', 'share_intent', etc.
  TextColumn get albumId => text().nullable()();
  IntColumn get favorite =>
      integer().withDefault(const Constant(0))(); // 0 or 1
  TextColumn get encryptedFilePath =>
      text()(); // /data/data/.../files/vault/objects/{id}.photo.enc
  TextColumn get thumbnailPath =>
      text()(); // /data/data/.../files/vault/objects/{id}.thumb.enc
  TextColumn get thumbnailNonce =>
      text()(); // base64-encoded nonce for thumbnail decryption
  TextColumn get photoNonce =>
      text()(); // base64-encoded nonce for photo decryption
  TextColumn get wrappedDek =>
      text()(); // JSON-encoded WrappedKey { nonce, ciphertext, mac }
  IntColumn get encryptionVersion =>
      integer()(); // for future key rotation/migration
  TextColumn get syncStatus =>
      text()(); // 'local', 'pending', 'synced', 'error'
  TextColumn get backupStatus =>
      text()(); // 'not_backed_up', 'pending', 'backed_up', 'error'
  TextColumn get checksumSha256 =>
      text()(); // SHA256 hash of original file (for duplicate detection)
  IntColumn get fileSize => integer()(); // in bytes
  TextColumn get mimeType => text()(); // 'image/jpeg', 'image/png', etc.
  IntColumn get isTrashed =>
      integer().withDefault(const Constant(0))(); // 0 or 1
  IntColumn get trashExpiresAtMs =>
      integer().nullable()(); // Unix timestamp when trash item auto-deletes
  IntColumn get deletedTombstoneAtMs =>
      integer().nullable()(); // For cloud sync tombstone cleanup

  @override
  Set<Column> get primaryKey => {id};
}

/// Albums: user-created folders for organizing photos.
@DataClassName('VaultAlbum')
class Albums extends Table {
  TextColumn get id => text()();
  TextColumn get name => text()();
  IntColumn get createdAtMs => integer()();
  IntColumn get updatedAtMs => integer()();

  @override
  Set<Column> get primaryKey => {id};
}

/// Tags: flexible tagging system for photos.
@DataClassName('VaultTag')
class Tags extends Table {
  TextColumn get id => text()();
  TextColumn get name => text()();
  IntColumn get createdAtMs => integer()();

  @override
  Set<Column> get primaryKey => {id};
}

/// Many-to-many: link photos to tags.
@DataClassName('PhotoTagLink')
class PhotoTags extends Table {
  TextColumn get photoId => text()();
  TextColumn get tagId => text()();

  @override
  Set<Column> get primaryKey => {photoId, tagId};
}

/// Vault metadata: tracks vault creation, mode, key versions.
@DataClassName('VaultMetadata')
class Vault extends Table {
  TextColumn get id => text()();
  TextColumn get mode => text()(); // 'local_only', 'google_enabled'
  IntColumn get createdAtMs => integer()();
  IntColumn get vmkWrapVersion => integer()(); // for key rotation
  IntColumn get activeEncryptionVersion => integer()(); // AES-256-GCM or future

  @override
  Set<Column> get primaryKey => {id};
}

/// Thumbnails: separate table for efficient thumbnail lifecycle.
@DataClassName('VaultThumbnail')
class Thumbnails extends Table {
  TextColumn get id => text()();
  TextColumn get photoId => text()();
  TextColumn get encryptedPath => text()();
  TextColumn get nonce => text()();
  IntColumn get encryptionVersion => integer()();
  IntColumn get width => integer()();
  IntColumn get height => integer()();
  TextColumn get checksumSha256 => text()();

  @override
  Set<Column> get primaryKey => {id};
}

/// Sync state: tracks which objects need sync to cloud.
@DataClassName('SyncStateEntry')
class SyncState extends Table {
  TextColumn get objectId => text()();
  TextColumn get objectType => text()(); // 'photo', 'album', 'tag'
  IntColumn get localVersion => integer()(); // for conflict detection
  IntColumn get remoteVersion => integer().nullable()();
  TextColumn get state =>
      text()(); // 'local_new', 'pending', 'synced', 'conflict', 'error'
  IntColumn get retryCount => integer().withDefault(const Constant(0))();
  IntColumn get updatedAtMs => integer()();

  @override
  Set<Column> get primaryKey => {objectId};
}

/// Backup state: tracks incremental backup progress.
@DataClassName('BackupStateEntry')
class BackupState extends Table {
  TextColumn get key =>
      text()(); // e.g., 'last_vmk_backup_ms', 'last_photo_sync_ms'
  TextColumn get value => text()();
  IntColumn get updatedAtMs => integer()();

  @override
  Set<Column> get primaryKey => {key};
}

/// Encryption versions: for future key rotation support.
@DataClassName('EncryptionVersionEntry')
class EncryptionVersions extends Table {
  IntColumn get version => integer()();
  TextColumn get cipher => text()(); // 'AES-256-GCM'
  TextColumn get kdf => text()(); // 'PBKDF2'
  TextColumn get paramsJson =>
      text()(); // JSON params: iterations, salt length, etc.
  IntColumn get active => integer().withDefault(const Constant(0))(); // 0 or 1

  @override
  Set<Column> get primaryKey => {version};
}

/// Import jobs: track multi-file import progress.
@DataClassName('ImportJobEntry')
class ImportJobs extends Table {
  TextColumn get id => text()();
  TextColumn get source => text()(); // 'camera', 'gallery', 'file_picker'
  IntColumn get totalItems => integer()();
  IntColumn get completedItems => integer()();
  IntColumn get failedItems => integer()();
  TextColumn get status => text()(); // 'running', 'completed', 'failed'
  IntColumn get createdAtMs => integer()();
  IntColumn get updatedAtMs => integer()();

  @override
  Set<Column> get primaryKey => {id};
}

/// Share/export records: track generated export packages.
@DataClassName('ShareExportEntry')
class ShareExports extends Table {
  TextColumn get id => text()();
  TextColumn get photoId => text().nullable()();
  TextColumn get exportMode => text()(); // 'encrypted', 'decrypted'
  TextColumn get packagePath => text()();
  IntColumn get expiresAtMs => integer().nullable()();
  IntColumn get createdAtMs => integer()();

  @override
  Set<Column> get primaryKey => {id};
}

/// Trash: soft-delete with auto-expiry.
@DataClassName('TrashItem')
class TrashItems extends Table {
  TextColumn get photoId => text()();
  IntColumn get movedAtMs => integer()();
  IntColumn get expiresAtMs => integer()(); // Unix timestamp for auto-delete
  IntColumn get syncDeletePending =>
      integer().withDefault(const Constant(0))(); // 0 or 1

  @override
  Set<Column> get primaryKey => {photoId};
}

/// App settings: user preferences (backup policy, etc.).
@DataClassName('AppSettingEntry')
class AppSettings extends Table {
  TextColumn get key => text()();
  TextColumn get value => text()();
  IntColumn get updatedAtMs => integer()();

  @override
  Set<Column> get primaryKey => {key};
}

/// Security events: audit log of sensitive actions (lock, unlock, export, restore, etc.).
@DataClassName('SecurityEvent')
class SecurityEvents extends Table {
  TextColumn get id => text()();
  TextColumn get eventType =>
      text()(); // 'unlock', 'lock', 'export', 'restore', etc.
  TextColumn get severity => text()(); // 'info', 'warning', 'critical'
  IntColumn get occurredAtMs => integer()();
  TextColumn get detailsJson =>
      text().nullable()(); // JSON object with event-specific details

  @override
  Set<Column> get primaryKey => {id};
}

/// Local cache of chat messages, so a thread opens instantly and stays
/// readable offline.
///
/// Stores the **ciphertext**, never the plaintext. This file is an ordinary
/// SQLite database with no encryption of its own, so caching decrypted bodies
/// would hand every past conversation to anyone who can read app storage —
/// defeating the end-to-end encryption. Decryption happens on read, using the
/// in-memory thread key, exactly as it does for messages fetched from
/// Firestore.
@DataClassName('CachedChatMessage')
class ChatMessages extends Table {
  TextColumn get messageId => text()();
  TextColumn get threadId => text()();
  TextColumn get senderId => text()();
  TextColumn get encryptedText => text()();
  IntColumn get sentAtMs => integer()();

  /// Verbatim `toFirestore()` JSON, so cached rows survive the addition of new
  /// message fields without a schema migration.
  TextColumn get payloadJson => text()();

  @override
  Set<Column> get primaryKey => {messageId};
}

/// Queued outgoing messages that have not reached Firestore yet.
///
/// Persisted rather than held in memory so a send survives the app being
/// killed while offline. The payload is already ciphertext — encryption happens
/// before queueing, so a queued message is no more readable on disk than a
/// cached one.
@DataClassName('OutboxEntry')
class OutboxMessages extends Table {
  TextColumn get messageId => text()();
  TextColumn get threadId => text()();
  TextColumn get senderId => text()();
  TextColumn get encryptedText => text()();

  /// Recipient, so the unread counter can still be bumped on delivery.
  TextColumn get recipientUid => text()();

  /// Plaintext-free preview already encrypted for the thread list, or a
  /// media placeholder like "📷 Photo".
  TextColumn get preview => text()();

  /// `MessageType.name`, null for plain text.
  TextColumn get mediaType => text().nullable()();

  /// Storage path if the upload already succeeded, otherwise null.
  TextColumn get mediaRef => text().nullable()();

  /// `MessageReply.toFirestore()` JSON, if this is a reply.
  TextColumn get replyJson => text().nullable()();

  IntColumn get queuedAtMs => integer()();
  IntColumn get attempts => integer().withDefault(const Constant(0))();
  TextColumn get lastError => text().nullable()();

  @override
  Set<Column> get primaryKey => {messageId};
}

// ============================================================================
// DATABASE CLASS
// ============================================================================

@DriftDatabase(
  tables: [
    Photos,
    Albums,
    Tags,
    PhotoTags,
    Vault,
    Thumbnails,
    SyncState,
    BackupState,
    EncryptionVersions,
    ImportJobs,
    ShareExports,
    TrashItems,
    AppSettings,
    SecurityEvents,
    ChatMessages,
    OutboxMessages,
  ],
)
class VaultDatabase extends _$VaultDatabase {
  VaultDatabase() : super(_openConnection());

  /// For tests, e.g. with `NativeDatabase.memory()`.
  VaultDatabase.forTesting(super.executor);

  @override
  int get schemaVersion => 4;

  @override
  MigrationStrategy get migration => MigrationStrategy(
    onCreate: (m) async {
      await m.createAll();
      await _createChatSearchSchema();
    },
    onUpgrade: (m, from, to) async {
      // v2 introduced the offline chat message cache. It holds only
      // ciphertext, so a failed migration can safely recreate it empty.
      if (from < 2) {
        await m.createTable(chatMessages);
      }
      // v3 introduced the offline send outbox.
      if (from < 3) {
        await m.createTable(outboxMessages);
      }
      // v4 introduced the keyed chat search index. Existing cached messages
      // are indexed lazily the next time their thread is opened.
      if (from < 4) {
        await _createChatSearchSchema();
      }
    },
  );

  /// Tables for the local chat search index.
  ///
  /// Declared in SQL rather than as Drift tables because they are accessed
  /// only through the hand-written queries below.
  ///
  /// `chat_search_tokens` holds keyed hashes of word prefixes (see
  /// `ChatSearchTokenizer`), never words, so — like `chat_messages` — it
  /// reveals no message content without the in-memory thread key.
  Future<void> _createChatSearchSchema() async {
    await customStatement(
      'CREATE INDEX IF NOT EXISTS idx_chat_messages_thread_sent '
      'ON chat_messages (thread_id, sent_at_ms)',
    );
    await customStatement(
      'CREATE TABLE IF NOT EXISTS chat_search_tokens ('
      'token TEXT NOT NULL, '
      'message_id TEXT NOT NULL, '
      'thread_id TEXT NOT NULL, '
      'sent_at_ms INTEGER NOT NULL, '
      'PRIMARY KEY (token, message_id)'
      ') WITHOUT ROWID',
    );
    await customStatement(
      'CREATE INDEX IF NOT EXISTS idx_chat_search_tokens_thread '
      'ON chat_search_tokens (thread_id, token, sent_at_ms DESC)',
    );
    await customStatement(
      'CREATE INDEX IF NOT EXISTS idx_chat_search_tokens_message '
      'ON chat_search_tokens (message_id)',
    );
    await customStatement(
      'CREATE TABLE IF NOT EXISTS chat_search_state ('
      'message_id TEXT NOT NULL PRIMARY KEY, '
      'thread_id TEXT NOT NULL, '
      'sent_at_ms INTEGER NOT NULL, '
      'version INTEGER NOT NULL'
      ') WITHOUT ROWID',
    );
    await customStatement(
      'CREATE INDEX IF NOT EXISTS idx_chat_search_state_thread '
      'ON chat_search_state (thread_id, sent_at_ms)',
    );
  }

  // =========================================================================
  // PHOTO QUERIES
  // =========================================================================

  /// Get non-trashed photos with pagination, ordered by most recent imported first.
  Future<List<VaultPhoto>> getGalleryPhotos({int? limit, int? offset}) async {
    final query = select(photos)
      ..where((p) => p.isTrashed.equals(0))
      ..orderBy([
        (p) => OrderingTerm(
          expression: p.importedTimeMs,
          mode: OrderingMode.desc,
        ),
      ]);
    if (limit != null) {
      query.limit(limit, offset: offset);
    }
    return query.get();
  }

  /// Get trashed photos with pagination.
  Future<List<VaultPhoto>> getTrashedPhotos({int? limit, int? offset}) async {
    final query = select(photos)
      ..where((p) => p.isTrashed.equals(1))
      ..orderBy([
        (p) => OrderingTerm(
          expression: p.trashExpiresAtMs,
          mode: OrderingMode.desc,
        ),
      ]);
    if (limit != null) {
      query.limit(limit, offset: offset);
    }
    return query.get();
  }

  /// Get all photos (including trashed) by album.
  Future<List<VaultPhoto>> getPhotosByAlbum(String albumId) async {
    return (select(photos)
          ..where((p) => p.albumId.equals(albumId) & p.isTrashed.equals(0))
          ..orderBy([
            (p) => OrderingTerm(
              expression: p.importedTimeMs,
              mode: OrderingMode.desc,
            ),
          ]))
        .get();
  }

  /// Check if checksum already exists (duplicate detection).
  Future<bool> photoWithChecksumExists(String checksum) async {
    final count =
        await (select(photos)..where(
              (p) => p.checksumSha256.equals(checksum) & p.isTrashed.equals(0),
            ))
            .get()
            .then((rows) => rows.length);
    return count > 0;
  }

  /// Get single photo by ID (for viewer/editor screens).
  Future<VaultPhoto?> getPhotoById(String id) async {
    return (select(photos)..where((p) => p.id.equals(id))).getSingleOrNull();
  }

  /// Insert new photo with metadata and encrypted file path.
  Future<void> insertPhoto(VaultPhoto photo) async {
    await into(photos).insert(photo);
  }

  /// Update photo (e.g., mark as favorite, move to album, update sync status).
  Future<void> updatePhoto(VaultPhoto photo) async {
    await update(photos).replace(photo);
  }

  /// Move photo to trash (soft delete).
  Future<void> movePhotoToTrash(String photoId, int expiresAtMs) async {
    final photo = await getPhotoById(photoId);
    if (photo != null) {
      await update(photos).replace(
        photo.copyWith(isTrashed: 1, trashExpiresAtMs: Value(expiresAtMs)),
      );
    }
  }

  /// Restore photo from trash.
  Future<void> restorePhotoFromTrash(String photoId) async {
    final photo = await getPhotoById(photoId);
    if (photo != null) {
      await update(photos).replace(
        photo.copyWith(isTrashed: 0, trashExpiresAtMs: const Value(null)),
      );
    }
  }

  /// Permanently delete photo (removes encrypted file marker for cleanup).
  Future<void> permanentlyDeletePhoto(String photoId) async {
    await (delete(photos)..where((p) => p.id.equals(photoId))).go();
    await (delete(photoTags)..where((pt) => pt.photoId.equals(photoId))).go();
  }

  /// Get all trashed photos with expiry < now (for cleanup job).
  Future<List<VaultPhoto>> getExpiredTrashPhotos(int nowMs) async {
    return (select(photos)..where(
          (p) =>
              p.isTrashed.equals(1) &
              (p.trashExpiresAtMs.isSmallerThanValue(nowMs) |
                  p.trashExpiresAtMs.isNull()),
        ))
        .get();
  }

  /// Count photos for gallery stats.
  Future<int> countPhotos({bool includeTrashed = false}) async {
    final query = select(photos);
    if (!includeTrashed) {
      query.where((p) => p.isTrashed.equals(0));
    }
    return query.get().then((rows) => rows.length);
  }

  // =========================================================================
  // TAG QUERIES
  // =========================================================================

  /// Get all tags.
  Future<List<VaultTag>> getAllTags() async {
    return select(tags).get();
  }

  /// Get tags for a specific photo.
  Future<List<VaultTag>> getTagsForPhoto(String photoId) async {
    final query = select(
      tags,
    ).join([innerJoin(photoTags, photoTags.tagId.equalsExp(tags.id))]);
    query.where(photoTags.photoId.equals(photoId));
    return query.map((row) => row.readTable(tags)).get();
  }

  /// Add tag to photo (many-to-many).
  Future<void> addTagToPhoto(String photoId, String tagId) async {
    await into(
      photoTags,
    ).insertOnConflictUpdate(PhotoTagLink(photoId: photoId, tagId: tagId));
  }

  /// Remove tag from photo.
  Future<void> removeTagFromPhoto(String photoId, String tagId) async {
    await (delete(
      photoTags,
    )..where((pt) => pt.photoId.equals(photoId) & pt.tagId.equals(tagId))).go();
  }

  // =========================================================================
  // ALBUM QUERIES
  // =========================================================================

  /// Get all albums.
  Future<List<VaultAlbum>> getAllAlbums() async {
    return select(albums).get();
  }

  /// Insert new album.
  Future<void> insertAlbum(VaultAlbum album) async {
    await into(albums).insert(album);
  }

  /// Update album.
  Future<void> updateAlbum(VaultAlbum album) async {
    await update(albums).replace(album);
  }

  // =========================================================================
  // TRASH QUERIES
  // =========================================================================

  /// Get trash items.
  Future<List<TrashItem>> getTrashItems() async {
    return (select(trashItems)..orderBy([
          (t) => OrderingTerm(expression: t.movedAtMs, mode: OrderingMode.desc),
        ]))
        .get();
  }

  /// Add to trash.
  Future<void> addToTrash(String photoId, int expiresAtMs) async {
    await into(trashItems).insertOnConflictUpdate(
      TrashItem(
        photoId: photoId,
        movedAtMs: DateTime.now().millisecondsSinceEpoch,
        expiresAtMs: expiresAtMs,
        syncDeletePending: 0,
      ),
    );
  }

  /// Remove from trash.
  Future<void> removeFromTrash(String photoId) async {
    await (delete(trashItems)..where((t) => t.photoId.equals(photoId))).go();
  }

  // =========================================================================
  // SYNC STATE QUERIES
  // =========================================================================

  /// Get all objects pending sync.
  Future<List<SyncStateEntry>> getPendingSyncItems() async {
    return (select(
      syncState,
    )..where((s) => s.state.isIn(['local_new', 'pending', 'error']))).get();
  }

  /// Update sync state.
  Future<void> updateSyncState(SyncStateEntry entry) async {
    await update(syncState).replace(entry);
  }

  // =========================================================================
  // BACKUP STATE QUERIES
  // =========================================================================

  /// Get backup state value.
  Future<String?> getBackupStateValue(String key) async {
    final entry = await (select(
      backupState,
    )..where((bs) => bs.key.equals(key))).getSingleOrNull();
    return entry?.value;
  }

  /// Set backup state value.
  Future<void> setBackupStateValue(String key, String value) async {
    await into(backupState).insertOnConflictUpdate(
      BackupStateEntry(
        key: key,
        value: value,
        updatedAtMs: DateTime.now().millisecondsSinceEpoch,
      ),
    );
  }

  // =========================================================================
  // VAULT METADATA QUERIES
  // =========================================================================

  /// Get vault metadata.
  Future<VaultMetadata?> getVaultMetadata(String vaultId) async {
    return (select(
      vault,
    )..where((v) => v.id.equals(vaultId))).getSingleOrNull();
  }

  /// Insert vault metadata.
  Future<void> insertVaultMetadata(VaultMetadata metadata) async {
    await into(vault).insert(metadata);
  }

  // =========================================================================
  // CLEANUP & MAINTENANCE
  // =========================================================================

  /// Clean up expired trash items and their associated database records.
  Future<int> cleanupExpiredTrash(int nowMs) async {
    final expiredPhotos = await getExpiredTrashPhotos(nowMs);
    for (final photo in expiredPhotos) {
      await permanentlyDeletePhoto(photo.id);
      await removeFromTrash(photo.id);
    }
    return expiredPhotos.length;
  }

  /// Log security event.
  Future<void> logSecurityEvent({
    required String id,
    required String eventType,
    required String severity,
    Map<String, dynamic>? details,
  }) async {
    await into(securityEvents).insert(
      SecurityEvent(
        id: id,
        eventType: eventType,
        severity: severity,
        occurredAtMs: DateTime.now().millisecondsSinceEpoch,
        detailsJson: details != null ? _jsonEncode(details) : null,
      ),
    );
  }

  // =========================================================================
  // CHAT MESSAGE CACHE
  // =========================================================================

  /// Newest-first page of cached messages for a thread.
  Future<List<CachedChatMessage>> getCachedMessages(
    String threadId, {
    int limit = 50,
    int? beforeSentAtMs,
  }) async {
    final query = select(chatMessages)
      ..where(
        (m) => beforeSentAtMs == null
            ? m.threadId.equals(threadId)
            : m.threadId.equals(threadId) &
                  m.sentAtMs.isSmallerThanValue(beforeSentAtMs),
      )
      ..orderBy([
        (m) => OrderingTerm(expression: m.sentAtMs, mode: OrderingMode.desc),
      ])
      ..limit(limit);
    return query.get();
  }

  /// Insert or refresh cached messages.
  Future<void> upsertCachedMessages(List<CachedChatMessage> rows) async {
    if (rows.isEmpty) return;
    await batch((b) => b.insertAllOnConflictUpdate(chatMessages, rows));
  }

  /// Drop a single cached message, used when it is deleted for everyone.
  Future<void> deleteCachedMessage(String messageId) async {
    await transaction(() async {
      await (delete(
        chatMessages,
      )..where((m) => m.messageId.equals(messageId))).go();
      await removeFromSearchIndex([messageId]);
    });
  }

  /// Drop an entire thread's cache.
  Future<void> deleteCachedThread(String threadId) async {
    await transaction(() async {
      await (delete(
        chatMessages,
      )..where((m) => m.threadId.equals(threadId))).go();
      await clearSearchIndexForThread(threadId);
    });
  }

  /// A single cached message, if present.
  Future<CachedChatMessage?> getCachedMessage(String messageId) {
    return (select(
      chatMessages,
    )..where((m) => m.messageId.equals(messageId))).getSingleOrNull();
  }

  /// Oldest-first page of cached messages sent at or after [fromSentAtMs].
  Future<List<CachedChatMessage>> getCachedMessagesFrom(
    String threadId, {
    required int fromSentAtMs,
    int limit = 50,
  }) {
    return (select(chatMessages)
          ..where(
            (m) =>
                m.threadId.equals(threadId) &
                m.sentAtMs.isBiggerOrEqualValue(fromSentAtMs),
          )
          ..orderBy([
            (m) => OrderingTerm(expression: m.sentAtMs),
            (m) => OrderingTerm(expression: m.messageId),
          ])
          ..limit(limit))
        .get();
  }

  /// Number of cached messages in a thread, optionally only those strictly
  /// older than [beforeSentAtMs].
  Future<int> countCachedMessages(String threadId, {int? beforeSentAtMs}) async {
    final count = chatMessages.messageId.count();
    final query = selectOnly(chatMessages)
      ..addColumns([count])
      ..where(
        beforeSentAtMs == null
            ? chatMessages.threadId.equals(threadId)
            : chatMessages.threadId.equals(threadId) &
                  chatMessages.sentAtMs.isSmallerThanValue(beforeSentAtMs),
      );
    return (await query.getSingle()).read(count) ?? 0;
  }

  /// The cached message [offset] positions from the oldest (0 = oldest).
  Future<CachedChatMessage?> getCachedMessageAtOffset(
    String threadId,
    int offset,
  ) {
    return (select(chatMessages)
          ..where((m) => m.threadId.equals(threadId))
          ..orderBy([
            (m) => OrderingTerm(expression: m.sentAtMs),
            (m) => OrderingTerm(expression: m.messageId),
          ])
          ..limit(1, offset: offset < 0 ? 0 : offset))
        .getSingleOrNull();
  }

  /// Oldest and newest cached send times in a thread, or null if empty.
  Future<(int, int)?> getCachedTimeBounds(String threadId) async {
    final min = chatMessages.sentAtMs.min();
    final max = chatMessages.sentAtMs.max();
    final row =
        await (selectOnly(chatMessages)
              ..addColumns([min, max])
              ..where(chatMessages.threadId.equals(threadId)))
            .getSingle();
    final lo = row.read(min);
    final hi = row.read(max);
    if (lo == null || hi == null) return null;
    return (lo, hi);
  }

  // =========================================================================
  // CHAT SEARCH INDEX
  // =========================================================================

  /// Replace the index entries of each message with its [tokens].
  Future<void> indexChatMessages(
    String threadId,
    List<({String messageId, int sentAtMs, List<String> tokens})> entries, {
    required int version,
  }) async {
    if (entries.isEmpty) return;
    await transaction(() async {
      await removeFromSearchIndex([for (final e in entries) e.messageId]);
      await batch((b) {
        for (final e in entries) {
          for (final token in e.tokens) {
            b.customStatement(
              'INSERT OR IGNORE INTO chat_search_tokens '
              '(token, message_id, thread_id, sent_at_ms) VALUES (?, ?, ?, ?)',
              [token, e.messageId, threadId, e.sentAtMs],
            );
          }
          b.customStatement(
            'INSERT OR REPLACE INTO chat_search_state '
            '(message_id, thread_id, sent_at_ms, version) VALUES (?, ?, ?, ?)',
            [e.messageId, threadId, e.sentAtMs, version],
          );
        }
      });
    });
  }

  Future<void> removeFromSearchIndex(List<String> messageIds) async {
    if (messageIds.isEmpty) return;
    for (var i = 0; i < messageIds.length; i += 500) {
      final chunk = messageIds.sublist(
        i,
        i + 500 > messageIds.length ? messageIds.length : i + 500,
      );
      final marks = List.filled(chunk.length, '?').join(',');
      await customStatement(
        'DELETE FROM chat_search_tokens WHERE message_id IN ($marks)',
        chunk,
      );
      await customStatement(
        'DELETE FROM chat_search_state WHERE message_id IN ($marks)',
        chunk,
      );
    }
  }

  Future<void> clearSearchIndexForThread(String threadId) async {
    await customStatement(
      'DELETE FROM chat_search_tokens WHERE thread_id = ?',
      [threadId],
    );
    await customStatement(
      'DELETE FROM chat_search_state WHERE thread_id = ?',
      [threadId],
    );
  }

  /// Ids and send times of messages containing *every* token, newest first.
  Future<List<({String messageId, int sentAtMs})>> searchChatIndex(
    String threadId,
    List<String> tokens, {
    int limit = 10000,
  }) async {
    final unique = tokens.toSet().toList();
    if (unique.isEmpty) return const [];
    final marks = List.filled(unique.length, '?').join(',');
    final rows = await customSelect(
      'SELECT message_id, MAX(sent_at_ms) AS sent_at_ms '
      'FROM chat_search_tokens '
      'WHERE thread_id = ? AND token IN ($marks) '
      'GROUP BY message_id '
      'HAVING COUNT(DISTINCT token) = ? '
      'ORDER BY sent_at_ms DESC, message_id DESC '
      'LIMIT ?',
      variables: [
        Variable<String>(threadId),
        for (final t in unique) Variable<String>(t),
        Variable<int>(unique.length),
        Variable<int>(limit),
      ],
    ).get();
    return [
      for (final r in rows)
        (
          messageId: r.read<String>('message_id'),
          sentAtMs: r.read<int>('sent_at_ms'),
        ),
    ];
  }

  /// Cached messages not yet indexed at [version], newest first.
  Future<List<CachedChatMessage>> getUnindexedCachedMessages(
    String threadId, {
    required int version,
    int limit = 200,
  }) async {
    final rows = await customSelect(
      'SELECT m.* FROM chat_messages m '
      'LEFT JOIN chat_search_state s '
      'ON s.message_id = m.message_id AND s.version >= ? '
      'WHERE m.thread_id = ? AND s.message_id IS NULL '
      'ORDER BY m.sent_at_ms DESC LIMIT ?',
      variables: [
        Variable<int>(version),
        Variable<String>(threadId),
        Variable<int>(limit),
      ],
      readsFrom: {chatMessages},
    ).get();
    return [for (final r in rows) chatMessages.map(r.data)];
  }

  /// How many cached messages still need indexing at [version].
  Future<int> countUnindexedCachedMessages(
    String threadId, {
    required int version,
  }) async {
    final row = await customSelect(
      'SELECT COUNT(*) AS c FROM chat_messages m '
      'LEFT JOIN chat_search_state s '
      'ON s.message_id = m.message_id AND s.version >= ? '
      'WHERE m.thread_id = ? AND s.message_id IS NULL',
      variables: [Variable<int>(version), Variable<String>(threadId)],
      readsFrom: {chatMessages},
    ).getSingle();
    return row.read<int>('c');
  }

  /// Every cached message in a thread, oldest-last, for in-chat search.
  Future<List<CachedChatMessage>> getAllCachedMessages(String threadId) async {
    return (select(chatMessages)
          ..where((m) => m.threadId.equals(threadId))
          ..orderBy([
            (m) => OrderingTerm(
              expression: m.sentAtMs,
              mode: OrderingMode.desc,
            ),
          ]))
        .get();
  }

  /// Every cached message across all threads, for chat backups.
  Future<List<CachedChatMessage>> getEveryCachedMessage() {
    return select(chatMessages).get();
  }

  /// Settings rows whose key starts with [prefix].
  Future<List<AppSettingEntry>> getAppSettingsWithPrefix(String prefix) {
    return (select(appSettings)..where((s) => s.key.like('$prefix%'))).get();
  }

  // =========================================================================
  // OUTBOX QUERIES
  // =========================================================================

  /// Queue a message for delivery, oldest first on read.
  Future<void> enqueueOutbox(OutboxMessagesCompanion entry) async {
    await into(outboxMessages).insertOnConflictUpdate(entry);
  }

  Future<List<OutboxEntry>> getOutboxEntries() {
    return (select(outboxMessages)..orderBy([
          (o) => OrderingTerm(expression: o.queuedAtMs),
        ]))
        .get();
  }

  Future<List<OutboxEntry>> getOutboxForThread(String threadId) {
    return (select(outboxMessages)
          ..where((o) => o.threadId.equals(threadId))
          ..orderBy([(o) => OrderingTerm(expression: o.queuedAtMs)]))
        .get();
  }

  Future<void> deleteOutboxEntry(String messageId) async {
    await (delete(
      outboxMessages,
    )..where((o) => o.messageId.equals(messageId))).go();
  }

  /// Record a failed attempt so the UI can show the message as unsent.
  Future<void> markOutboxFailure(String messageId, String error) async {
    final row = await (select(
      outboxMessages,
    )..where((o) => o.messageId.equals(messageId))).getSingleOrNull();
    if (row == null) return;
    await (update(outboxMessages)
          ..where((o) => o.messageId.equals(messageId)))
        .write(
          OutboxMessagesCompanion(
            attempts: Value(row.attempts + 1),
            lastError: Value(error),
          ),
        );
  }

  /// Generic key/value settings row, reused for small per-device flags (e.g.
  /// the local "clear chat" watermark) that do not need a dedicated table.
  Future<void> upsertAppSetting(String key, String value) async {
    await into(appSettings).insertOnConflictUpdate(
      AppSettingsCompanion.insert(
        key: key,
        value: value,
        updatedAtMs: DateTime.now().toUtc().millisecondsSinceEpoch,
      ),
    );
  }

  Future<String?> getAppSetting(String key) async {
    final row = await (select(
      appSettings,
    )..where((s) => s.key.equals(key))).getSingleOrNull();
    return row?.value;
  }

  Future<void> deleteAppSetting(String key) async {
    await (delete(appSettings)..where((s) => s.key.equals(key))).go();
  }

  /// Clear all tables (for testing or reset vault).
  Future<void> clearAllTables() async {
    await delete(photos).go();
    await delete(albums).go();
    await delete(tags).go();
    await delete(photoTags).go();
    await delete(vault).go();
    await delete(thumbnails).go();
    await delete(syncState).go();
    await delete(backupState).go();
    await delete(encryptionVersions).go();
    await delete(importJobs).go();
    await delete(shareExports).go();
    await delete(trashItems).go();
    await delete(appSettings).go();
    await delete(securityEvents).go();
    await delete(chatMessages).go();
    await customStatement('DELETE FROM chat_search_tokens');
    await customStatement('DELETE FROM chat_search_state');
  }

  static String _jsonEncode(Map<String, dynamic> data) => data.toString();
}

// ============================================================================
// DATABASE CONNECTION FACTORY
// ============================================================================

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    // Using driftDatabase helper from drift_flutter
    // It automatically handles SQLite setup for Flutter
    return driftDatabase(name: 'vault');
  });
}
