import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';

// This file will be generated by build_runner.
// Run: flutter pub run build_runner build
// Generated file: vault_database.g.dart

part 'vault_database.g.dart';

// ============================================================================
// TABLE DEFINITIONS
// ============================================================================

/// Photos table: encrypted photo metadata including file paths, keys, and checksums.
@DataClassName('VaultPhoto')
class Photos extends Table {
  TextColumn get id => text()();
  TextColumn get originalFilename => text()();
  IntColumn get createdTimeMs => integer()();
  IntColumn get importedTimeMs => integer()();
  IntColumn get modifiedTimeMs => integer()();
  TextColumn get source =>
      text()(); // 'camera', 'gallery', 'file_picker', 'share_intent', etc.
  TextColumn get albumId => text().nullable()();
  IntColumn get favorite =>
      integer().withDefault(const Constant(0))(); // 0 or 1
  TextColumn get encryptedFilePath =>
      text()(); // /data/data/.../files/vault/objects/{id}.photo.enc
  TextColumn get thumbnailPath =>
      text()(); // /data/data/.../files/vault/objects/{id}.thumb.enc
  TextColumn get thumbnailNonce =>
      text()(); // base64-encoded nonce for thumbnail decryption
  TextColumn get photoNonce =>
      text()(); // base64-encoded nonce for photo decryption
  TextColumn get wrappedDek =>
      text()(); // JSON-encoded WrappedKey { nonce, ciphertext, mac }
  IntColumn get encryptionVersion =>
      integer()(); // for future key rotation/migration
  TextColumn get syncStatus =>
      text()(); // 'local', 'pending', 'synced', 'error'
  TextColumn get backupStatus =>
      text()(); // 'not_backed_up', 'pending', 'backed_up', 'error'
  TextColumn get checksumSha256 =>
      text()(); // SHA256 hash of original file (for duplicate detection)
  IntColumn get fileSize => integer()(); // in bytes
  TextColumn get mimeType => text()(); // 'image/jpeg', 'image/png', etc.
  IntColumn get isTrashed =>
      integer().withDefault(const Constant(0))(); // 0 or 1
  IntColumn get trashExpiresAtMs =>
      integer().nullable()(); // Unix timestamp when trash item auto-deletes
  IntColumn get deletedTombstoneAtMs =>
      integer().nullable()(); // For cloud sync tombstone cleanup

  @override
  Set<Column> get primaryKey => {id};
}

/// Albums: user-created folders for organizing photos.
@DataClassName('VaultAlbum')
class Albums extends Table {
  TextColumn get id => text()();
  TextColumn get name => text()();
  IntColumn get createdAtMs => integer()();
  IntColumn get updatedAtMs => integer()();

  @override
  Set<Column> get primaryKey => {id};
}

/// Tags: flexible tagging system for photos.
@DataClassName('VaultTag')
class Tags extends Table {
  TextColumn get id => text()();
  TextColumn get name => text()();
  IntColumn get createdAtMs => integer()();

  @override
  Set<Column> get primaryKey => {id};
}

/// Many-to-many: link photos to tags.
@DataClassName('PhotoTagLink')
class PhotoTags extends Table {
  TextColumn get photoId => text()();
  TextColumn get tagId => text()();

  @override
  Set<Column> get primaryKey => {photoId, tagId};
}

/// Vault metadata: tracks vault creation, mode, key versions.
@DataClassName('VaultMetadata')
class Vault extends Table {
  TextColumn get id => text()();
  TextColumn get mode => text()(); // 'local_only', 'google_enabled'
  IntColumn get createdAtMs => integer()();
  IntColumn get vmkWrapVersion => integer()(); // for key rotation
  IntColumn get activeEncryptionVersion => integer()(); // AES-256-GCM or future

  @override
  Set<Column> get primaryKey => {id};
}

/// Thumbnails: separate table for efficient thumbnail lifecycle.
@DataClassName('VaultThumbnail')
class Thumbnails extends Table {
  TextColumn get id => text()();
  TextColumn get photoId => text()();
  TextColumn get encryptedPath => text()();
  TextColumn get nonce => text()();
  IntColumn get encryptionVersion => integer()();
  IntColumn get width => integer()();
  IntColumn get height => integer()();
  TextColumn get checksumSha256 => text()();

  @override
  Set<Column> get primaryKey => {id};
}

/// Sync state: tracks which objects need sync to cloud.
@DataClassName('SyncStateEntry')
class SyncState extends Table {
  TextColumn get objectId => text()();
  TextColumn get objectType => text()(); // 'photo', 'album', 'tag'
  IntColumn get localVersion => integer()(); // for conflict detection
  IntColumn get remoteVersion => integer().nullable()();
  TextColumn get state =>
      text()(); // 'local_new', 'pending', 'synced', 'conflict', 'error'
  IntColumn get retryCount => integer().withDefault(const Constant(0))();
  IntColumn get updatedAtMs => integer()();

  @override
  Set<Column> get primaryKey => {objectId};
}

/// Backup state: tracks incremental backup progress.
@DataClassName('BackupStateEntry')
class BackupState extends Table {
  TextColumn get key =>
      text()(); // e.g., 'last_vmk_backup_ms', 'last_photo_sync_ms'
  TextColumn get value => text()();
  IntColumn get updatedAtMs => integer()();

  @override
  Set<Column> get primaryKey => {key};
}

/// Encryption versions: for future key rotation support.
@DataClassName('EncryptionVersionEntry')
class EncryptionVersions extends Table {
  IntColumn get version => integer()();
  TextColumn get cipher => text()(); // 'AES-256-GCM'
  TextColumn get kdf => text()(); // 'PBKDF2'
  TextColumn get paramsJson =>
      text()(); // JSON params: iterations, salt length, etc.
  IntColumn get active => integer().withDefault(const Constant(0))(); // 0 or 1

  @override
  Set<Column> get primaryKey => {version};
}

/// Import jobs: track multi-file import progress.
@DataClassName('ImportJobEntry')
class ImportJobs extends Table {
  TextColumn get id => text()();
  TextColumn get source => text()(); // 'camera', 'gallery', 'file_picker'
  IntColumn get totalItems => integer()();
  IntColumn get completedItems => integer()();
  IntColumn get failedItems => integer()();
  TextColumn get status => text()(); // 'running', 'completed', 'failed'
  IntColumn get createdAtMs => integer()();
  IntColumn get updatedAtMs => integer()();

  @override
  Set<Column> get primaryKey => {id};
}

/// Share/export records: track generated export packages.
@DataClassName('ShareExportEntry')
class ShareExports extends Table {
  TextColumn get id => text()();
  TextColumn get photoId => text().nullable()();
  TextColumn get exportMode => text()(); // 'encrypted', 'decrypted'
  TextColumn get packagePath => text()();
  IntColumn get expiresAtMs => integer().nullable()();
  IntColumn get createdAtMs => integer()();

  @override
  Set<Column> get primaryKey => {id};
}

/// Trash: soft-delete with auto-expiry.
@DataClassName('TrashItem')
class TrashItems extends Table {
  TextColumn get photoId => text()();
  IntColumn get movedAtMs => integer()();
  IntColumn get expiresAtMs => integer()(); // Unix timestamp for auto-delete
  IntColumn get syncDeletePending =>
      integer().withDefault(const Constant(0))(); // 0 or 1

  @override
  Set<Column> get primaryKey => {photoId};
}

/// App settings: user preferences (biometric enabled, backup policy, etc.).
@DataClassName('AppSettingEntry')
class AppSettings extends Table {
  TextColumn get key => text()();
  TextColumn get value => text()();
  IntColumn get updatedAtMs => integer()();

  @override
  Set<Column> get primaryKey => {key};
}

/// Security events: audit log of sensitive actions (lock, unlock, export, restore, etc.).
@DataClassName('SecurityEvent')
class SecurityEvents extends Table {
  TextColumn get id => text()();
  TextColumn get eventType =>
      text()(); // 'unlock', 'lock', 'export', 'restore', etc.
  TextColumn get severity => text()(); // 'info', 'warning', 'critical'
  IntColumn get occurredAtMs => integer()();
  TextColumn get detailsJson =>
      text().nullable()(); // JSON object with event-specific details

  @override
  Set<Column> get primaryKey => {id};
}

// ============================================================================
// DATABASE CLASS
// ============================================================================

@DriftDatabase(
  tables: [
    Photos,
    Albums,
    Tags,
    PhotoTags,
    Vault,
    Thumbnails,
    SyncState,
    BackupState,
    EncryptionVersions,
    ImportJobs,
    ShareExports,
    TrashItems,
    AppSettings,
    SecurityEvents,
  ],
)
class VaultDatabase extends _$VaultDatabase {
  VaultDatabase() : super(_openConnection());

  @override
  int get schemaVersion => 1;

  // =========================================================================
  // PHOTO QUERIES
  // =========================================================================

  /// Get all non-trashed photos, ordered by most recent imported first.
  Future<List<VaultPhoto>> getGalleryPhotos() async {
    return (select(photos)
          ..where((p) => p.isTrashed.equals(0))
          ..orderBy([
            (p) => OrderingTerm(
              expression: p.importedTimeMs,
              mode: OrderingMode.desc,
            ),
          ]))
        .get();
  }

  /// Get all photos (including trashed) by album.
  Future<List<VaultPhoto>> getPhotosByAlbum(String albumId) async {
    return (select(photos)
          ..where((p) => p.albumId.equals(albumId) & p.isTrashed.equals(0))
          ..orderBy([
            (p) => OrderingTerm(
              expression: p.importedTimeMs,
              mode: OrderingMode.desc,
            ),
          ]))
        .get();
  }

  /// Check if checksum already exists (duplicate detection).
  Future<bool> photoWithChecksumExists(String checksum) async {
    final count =
        await (select(photos)..where(
              (p) => p.checksumSha256.equals(checksum) & p.isTrashed.equals(0),
            ))
            .get()
            .then((rows) => rows.length);
    return count > 0;
  }

  /// Get single photo by ID (for viewer/editor screens).
  Future<VaultPhoto?> getPhotoById(String id) async {
    return (select(photos)..where((p) => p.id.equals(id))).getSingleOrNull();
  }

  /// Insert new photo with metadata and encrypted file path.
  Future<void> insertPhoto(VaultPhoto photo) async {
    await into(photos).insert(photo);
  }

  /// Update photo (e.g., mark as favorite, move to album, update sync status).
  Future<void> updatePhoto(VaultPhoto photo) async {
    await update(photos).replace(photo);
  }

  /// Move photo to trash (soft delete).
  Future<void> movePhotoToTrash(String photoId, int expiresAtMs) async {
    final photo = await getPhotoById(photoId);
    if (photo != null) {
      await update(photos).replace(
        photo.copyWith(isTrashed: 1, trashExpiresAtMs: Value(expiresAtMs)),
      );
    }
  }

  /// Restore photo from trash.
  Future<void> restorePhotoFromTrash(String photoId) async {
    final photo = await getPhotoById(photoId);
    if (photo != null) {
      await update(photos).replace(
        photo.copyWith(isTrashed: 0, trashExpiresAtMs: const Value(null)),
      );
    }
  }

  /// Permanently delete photo (removes encrypted file marker for cleanup).
  Future<void> permanentlyDeletePhoto(String photoId) async {
    await (delete(photos)..where((p) => p.id.equals(photoId))).go();
    await (delete(photoTags)..where((pt) => pt.photoId.equals(photoId))).go();
  }

  /// Get all trashed photos with expiry < now (for cleanup job).
  Future<List<VaultPhoto>> getExpiredTrashPhotos(int nowMs) async {
    return (select(photos)..where(
          (p) =>
              p.isTrashed.equals(1) &
              (p.trashExpiresAtMs.isSmallerThanValue(nowMs) |
                  p.trashExpiresAtMs.isNull()),
        ))
        .get();
  }

  /// Count photos for gallery stats.
  Future<int> countPhotos({bool includeTrashed = false}) async {
    final query = select(photos);
    if (!includeTrashed) {
      query.where((p) => p.isTrashed.equals(0));
    }
    return query.get().then((rows) => rows.length);
  }

  // =========================================================================
  // TAG QUERIES
  // =========================================================================

  /// Get all tags.
  Future<List<VaultTag>> getAllTags() async {
    return select(tags).get();
  }

  /// Get tags for a specific photo.
  Future<List<VaultTag>> getTagsForPhoto(String photoId) async {
    final query = select(
      tags,
    ).join([innerJoin(photoTags, photoTags.tagId.equalsExp(tags.id))]);
    query.where(photoTags.photoId.equals(photoId));
    return query.map((row) => row.readTable(tags)).get();
  }

  /// Add tag to photo (many-to-many).
  Future<void> addTagToPhoto(String photoId, String tagId) async {
    await into(
      photoTags,
    ).insertOnConflictUpdate(PhotoTagLink(photoId: photoId, tagId: tagId));
  }

  /// Remove tag from photo.
  Future<void> removeTagFromPhoto(String photoId, String tagId) async {
    await (delete(
      photoTags,
    )..where((pt) => pt.photoId.equals(photoId) & pt.tagId.equals(tagId))).go();
  }

  // =========================================================================
  // ALBUM QUERIES
  // =========================================================================

  /// Get all albums.
  Future<List<VaultAlbum>> getAllAlbums() async {
    return select(albums).get();
  }

  /// Insert new album.
  Future<void> insertAlbum(VaultAlbum album) async {
    await into(albums).insert(album);
  }

  /// Update album.
  Future<void> updateAlbum(VaultAlbum album) async {
    await update(albums).replace(album);
  }

  // =========================================================================
  // TRASH QUERIES
  // =========================================================================

  /// Get trash items.
  Future<List<TrashItem>> getTrashItems() async {
    return (select(trashItems)..orderBy([
          (t) => OrderingTerm(expression: t.movedAtMs, mode: OrderingMode.desc),
        ]))
        .get();
  }

  /// Add to trash.
  Future<void> addToTrash(String photoId, int expiresAtMs) async {
    await into(trashItems).insertOnConflictUpdate(
      TrashItem(
        photoId: photoId,
        movedAtMs: DateTime.now().millisecondsSinceEpoch,
        expiresAtMs: expiresAtMs,
        syncDeletePending: 0,
      ),
    );
  }

  /// Remove from trash.
  Future<void> removeFromTrash(String photoId) async {
    await (delete(trashItems)..where((t) => t.photoId.equals(photoId))).go();
  }

  // =========================================================================
  // SYNC STATE QUERIES
  // =========================================================================

  /// Get all objects pending sync.
  Future<List<SyncStateEntry>> getPendingSyncItems() async {
    return (select(
      syncState,
    )..where((s) => s.state.isIn(['local_new', 'pending', 'error']))).get();
  }

  /// Update sync state.
  Future<void> updateSyncState(SyncStateEntry entry) async {
    await update(syncState).replace(entry);
  }

  // =========================================================================
  // BACKUP STATE QUERIES
  // =========================================================================

  /// Get backup state value.
  Future<String?> getBackupStateValue(String key) async {
    final entry = await (select(
      backupState,
    )..where((bs) => bs.key.equals(key))).getSingleOrNull();
    return entry?.value;
  }

  /// Set backup state value.
  Future<void> setBackupStateValue(String key, String value) async {
    await into(backupState).insertOnConflictUpdate(
      BackupStateEntry(
        key: key,
        value: value,
        updatedAtMs: DateTime.now().millisecondsSinceEpoch,
      ),
    );
  }

  // =========================================================================
  // VAULT METADATA QUERIES
  // =========================================================================

  /// Get vault metadata.
  Future<VaultMetadata?> getVaultMetadata(String vaultId) async {
    return (select(
      vault,
    )..where((v) => v.id.equals(vaultId))).getSingleOrNull();
  }

  /// Insert vault metadata.
  Future<void> insertVaultMetadata(VaultMetadata metadata) async {
    await into(vault).insert(metadata);
  }

  // =========================================================================
  // CLEANUP & MAINTENANCE
  // =========================================================================

  /// Clean up expired trash items and their associated database records.
  Future<int> cleanupExpiredTrash(int nowMs) async {
    final expiredPhotos = await getExpiredTrashPhotos(nowMs);
    for (final photo in expiredPhotos) {
      await permanentlyDeletePhoto(photo.id);
      await removeFromTrash(photo.id);
    }
    return expiredPhotos.length;
  }

  /// Log security event.
  Future<void> logSecurityEvent({
    required String id,
    required String eventType,
    required String severity,
    Map<String, dynamic>? details,
  }) async {
    await into(securityEvents).insert(
      SecurityEvent(
        id: id,
        eventType: eventType,
        severity: severity,
        occurredAtMs: DateTime.now().millisecondsSinceEpoch,
        detailsJson: details != null ? _jsonEncode(details) : null,
      ),
    );
  }

  /// Clear all tables (for testing or reset vault).
  Future<void> clearAllTables() async {
    await delete(photos).go();
    await delete(albums).go();
    await delete(tags).go();
    await delete(photoTags).go();
    await delete(vault).go();
    await delete(thumbnails).go();
    await delete(syncState).go();
    await delete(backupState).go();
    await delete(encryptionVersions).go();
    await delete(importJobs).go();
    await delete(shareExports).go();
    await delete(trashItems).go();
    await delete(appSettings).go();
    await delete(securityEvents).go();
  }

  static String _jsonEncode(Map<String, dynamic> data) => data.toString();
}

// ============================================================================
// DATABASE CONNECTION FACTORY
// ============================================================================

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    // Using driftDatabase helper from drift_flutter
    // It automatically handles SQLite setup for Flutter
    return driftDatabase(name: 'vault');
  });
}
