// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5aVrcx0ipVEmLLxPP4L51i4chXn7-XU4',
    appId: '1:209716874258:web:6acffd73ac2268722cdccb',
    messagingSenderId: '209716874258',
    projectId: 'shadow4726262',
    authDomain: 'shadow4726262.firebaseapp.com',
    storageBucket: 'shadow4726262.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6WesaMeNOuFpEiVneL2Ftofxb2S9kKQA',
    appId: '1:209716874258:android:becd7304e0ba1b772cdccb',
    messagingSenderId: '209716874258',
    projectId: 'shadow4726262',
    storageBucket: 'shadow4726262.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5aVrcx0ipVEmLLxPP4L51i4chXn7-XU4',
    appId: '1:209716874258:web:17cdc5c7741a4ad32cdccb',
    messagingSenderId: '209716874258',
    projectId: 'shadow4726262',
    authDomain: 'shadow4726262.firebaseapp.com',
    storageBucket: 'shadow4726262.firebasestorage.app',
  );
}
